---
abstract: 'Find different-language pairs of books in a collection.'
author:
  - 'Andre Santos <andrefs@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Perfide-BookPairs
provides:
  Text::Perfide::BookPairs:
    file: lib/Text/Perfide/BookPairs.pm
    version: 0.01_03
requires:
  Data::Dumper: 0
  File::Basename: 0
  File::Path: 0
  Text::Perfide::BookCleaner: 0
  Text::Perfide::WordBags: 0
  perl: 5.006
  utf8::all: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_03
